### ISSUE TITLE
How Multi-tenant works in Hyku

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#1]
## Name
Rob Kaufman

## Institution
Notch8

## Title
How Multi-tenant works in Hyku

## Abstract
We'll go over the Apartment gem, what it means and how it is integrated in the the multi-tenant structure of Hyku.

## Audience
Developers, DevOps and System Administrators

## Format 
Long Presentation

## Date preference / Availability
Tuesday or Wednesday

## Streaming/Recording/Archiving Permission
Yes

**Comment by rsteans** [comment]
confirmed via Slack by Rob
