### ISSUE TITLE
Samvera headaches: the choice between flexibility and ease of maintenance with multiple and multipurpose repositories

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#13]
## Name
Richard Higgins

## Institution
Durham University Library

## Names of co-presenter(s)
Olli Lyytinen

## Title
Samvera headaches: the choice between flexibility and ease of maintenance with multiple and multipurpose repositories

## Abstract
"The presentation would start with a demonstration of the Samvera heads that we have developed for deploying and managing IIIF at Durham, looking particularly at what has worked and what has stretched the underlying Fedora repository to breaking point. In parallel we have developed a research data system based on Sufia and have now reached the stage where we need to either bring these systems together into a single package, or identify a clear break between where we should follow standard packages such as Hyrax and where local implementations are required. With developments like Valkyrie and the Oxford Common File System also imminent, it becomes tempting to just wait until they are released, further complicating the planning process.
It would be interesting to end with a discussion of the relative benefits of converging on one stable head or having a system that fulfills all institutional requirements, so this might work as part of a themed group of presentations."

## Audience
Developers, DevOps and System Administrators, Repository or DAMS Managers

## Format 
Longer presentation (approximately 20-30 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by chrissyrissmeyer** [comment]
Presenters are in the UK, so prefer an earlier presentation time slot.
