### ISSUE TITLE
Avalon Media System Update

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#15]
## Name
Jon Cameron

## Institution
Indiana University

## Names of co-presenter(s)
David Schober, Ryan Steans

## Title
Avalon Media System Update

## Abstract
This presentation will cover Avalon progress from the past year focusing on new features that will be available in both Avalon 6 and 7.  In addition to discussion of core components such as Batch Ingest, Transcoding, and IIIF manifest generation, the team will showcase new features available on Avalon 6 (with eyes toward 7) such as  OHMS integration, the Timeliner and the Structural Metadata editor.  We will give an update on planned work such as design for Avalon 7, playlists, user management features, and permissions as we work toward building Avalon 7. 

## Audience
DevOps and System Administrators, Repository or DAMS Managers, Metadata Specialists, Administrators

## Format 
Longer presentation (approximately 20-30 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by chrissyrissmeyer** [comment]
Jon confirmed that they are willing to do this as a lightning talk due to time constraints.
