### ISSUE TITLE
Samvera Roadmap Council Update

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#17]
## Name
Jen Young

## Institution
Northwestern University Libraries

## Title
Samvera Roadmap Council Update

## Abstract
A brief update on the work the Roadmap Council has done and will do since being constituted in October 2018. 

## Audience
All

## Format 
Interest Group / Working Group update (less than 5 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
Jen confirmed via Slack
