### ISSUE TITLE
Hyku: a multi-tenant, ready-to-ship Samvera implementation

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#2]
## Name
Rob Kaufman

## Institution
Notch8

## Names of co-presenter(s)
Kevin Kochanski

## Title
Hyku: a multi-tenant, ready-to-ship Samvera implementation

## Abstract
An introduction to Hyku. Hyku is a collaborative product that extends existing Samvera codebase in order to build, bundle, and promote a feature-rich, robust, flexible digital repository. Hyku's chief benefits are ease of installation, configuration, and maintenance.

## Audience
Repository or DAMS Managers, Administrators

## Format 
Lightning talk (less than 10 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
confirmed via Slack by Rob
