### ISSUE TITLE
Making Hyrax more inclusive through controlled vocabulary choice

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#20]
## Name
Julie Hardesty

## Institution
Indiana University

## Title
Making Hyrax more inclusive through controlled vocabulary choice

## Abstract
What if the Hyrax web application were to support and include, by default, controlled vocabularies from marginalized communities? Currently Hyrax supplies a default set of descriptive metadata fields for describing uploaded objects. This set of fields includes Keyword (a required field) and Subject (an optional field). Neither of these fields are controlled by a vocabulary of terms upon install. The Questioning Authority (QA) gem exists as an option to configure and apply controlled vocabularies for use with fields such as these in Hyrax. While QA can be configured to work with nearly any vocabulary, the current vocabularies offered through the gem when it is installed include LCSH/NAF/GFT/MPT/DGT, FAST, Geonames, MeSH, Agrovoc, DBPedia, NALT, and Getty (AAT, TGN, ULAN). These are widely used mainstream sources for topical subject and genre description but also tend to reflect the current dominant mainstream power structure in the United States (white, male, straight, able-bodied, middle-class, Christian, Anglo). Should we increase the list of vocabularies available, by default, in the QA gem? Should we go beyond that and enable vocabulary choices on the default Subject and Keyword Hyrax fields? This lightning talk will discuss these questions and consider vocabulary options that would provide more inclusive descriptive capabilities.

## Audience
Developers, Repository or DAMS Managers, Metadata Specialists

## Format 
Lightning talk (less than 10 minutes)

## Date preference / Availability
Tuesday April 23rd

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
Julie is out til next week.
