### ISSUE TITLE
Introducing NewspaperWorks

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#21]
## Name
Eben English

## Institution
Boston Public Library

## Title
Introducing NewspaperWorks

## Abstract
This talk will discuss NewspaperWorks, a gem that provides content models, batch ingest tasks, and front-end functionality for digitized newspaper content. The gem is intended to be installed in a Hyrax-based repository application, and can be used to add newspaper content to an existing repository, or create a stand-alone newspaper content interface.

## Audience
Developers, Repository or DAMS Managers, Metadata Specialists, Administrators

## Format 
Lightning talk (less than 10 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
Eben confirmed on Wednesday 03/13
