### ISSUE TITLE
An approach to File CRUD and attachment APIs

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#23]
## Name
Sean Upton

## Institution
University of Utah J. Willard Marriott Library

## Title
An approach to File CRUD and attachment APIs

## Abstract
Attaching files in Hyrax for purposes of ingest and other programmatic use is complicated.  This talk describes some challenges around file attachment, generally, and presents a wrapper API with simpler calling semantics both for access and attachment of primary and derivative files (and abstraction of associated operations usually buried in the actor stack or asynchronous jobs).  The adapter components providing this simple interface provide a uniform and succinct way for multiple ingests to have consistent behavior.  This brief talk will present the proposed "assign and commit" calling semantics around file attachment, and make the case as to why this approach is the best fit for how Hyrax and associated stack components implement file attachment process.  These components have been developed as part of the IMLS-funded Historic Newspapers in Samvera project.

## Audience
Developers, DevOps and System Administrators, Repository or DAMS Managers, Anyone building ingest processes

## Format 
Lightning talk (less than 10 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
Sean is available and confirmed
