### ISSUE TITLE
New Directions for Northwestern: Taking a Cloud-First Approach

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#25]
## Name
Michael B. Klein

## Institution
Northwestern University Libraries

## Names of co-presenter(s)
Adam Arling, Karen Shaw, Brendan Quinn, David Schober

## Title
New Directions for Northwestern: Taking a Cloud-First Approach

## Abstract
"Northwestern University Libraries is currently running Samvera applications in production. Three of these are developed, maintained, and managed by the Repository & Digital Curation workgroup:

* Arch, an Institutional Repository, based on Hyrax 2.4.1
* AVR, Northwestern's audiovisual repository, based on Avalon 6.3
* DONUT, the staff-facing ingest interface for the digital object repository, based on Hyrax 2.4.1

In developing and deploying these applications, we have encountered (and mostly overcome) numerous stumbling blocks relating to performance, scalability, customization, and assumptions about the deployment environment and infrastructure on which the apps will run. While we have found it possible to shoehorn the Samvera stack (as it exists today) into our Amazon Web Services cloud-based deployment environment, we have also started to investigate the rewards and compromises involved in taking a cloud-first approach to our next generation of tools. We have identified several basic tenets for this approach so far:

* If AWS offers a native Software-as-a-Service (SaaS) solution for a particular problem, use it (e.g., choose ElasticSearch/Cloud Search over Solr)
* Avoid virtual server instances that run 24x7 waiting for requests/work
* Do not assume there is a local filesystem to work with
* Optimize startup time so that units of work can be spawned and killed as needed
* Constantly assess and reassess every unit of work for scalability, repeatability, and idempotence
* Keep data portable and code adaptable, but don't over-stress about vendor lock-in

In this presentation, members of the Repository Development & Administration Team will present on lessons learned from 7 years of working with Samvera, Avalon, and Hyrax, what the future holds for our next round of in-house development, and the opportunities & compromises our cloud-first approach creates regarding our use of and contributions to the larger Samvera community."

## Audience
Developers, DevOps and System Administrators, Repository or DAMS Managers

## Format 
Longer presentation (approximately 20-30 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
Adam Arling confirmed via Slack
