### ISSUE TITLE
Fedora 6.0 and the Oxford Common File Layout

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#27]
## Name
David Wilcox

## Institution
DuraSpace

## Title
Fedora 6.0 and the Oxford Common File Layout

## Abstract
"For the past several years the Fedora community has prioritized alignment with linked data best practices and modern web standards. We are now shifting our attention back to Fedora's digital preservation roots with a focus on the Oxford Common File Layout (OCFL). The OFCL is an application-independent approach to the storage of digital objects in a structured, transparent, and predictable manner. Fedora 6.0, the next major release, will replace the current ModeShape backend with a more scalable and performant implementation that persists data in accordance with the OCFL specification. This presentation will provide an overview of the Fedora 6.0 design, including an introduction to the OCFL and how it will be implemented. It will be of interest to Samvera community members who want to track Fedora developments and understand their impact on Samvera applications.

Note: I am submitting this as a longer presentation but I could shorten it to a lightning talk if necessary."

## Audience
Developers, Repository or DAMS Managers

## Format 
Longer presentation (approximately 20-30 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by chrissyrissmeyer** [comment]
We are going to ask David if he can do this as a lightning talk, as offered, due to time constraints.
