### ISSUE TITLE
Samvera Marketing WG update - selling Samvera

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#28]
## Name
Chris Awre

## Institution
University of Hull

## Title
Samvera Marketing WG update - selling Samvera

## Abstract
We wish to share the ongoing work of the Samvera Marketing WG following its initiation in 2018.  The goal for this year is to raise awareness of Samvera amongst different audiences that Samvera works with, both within our organisations and with potential new members of the community. Ideas, as ever, of what sells Samvera for you are welcome!

## Audience
Developers, DevOps and System Administrators, Repository or DAMS Managers, Metadata Specialists, Administrators, Senior Managers

## Format 
Interest Group / Working Group update (less than 5 minutes)

## Date preference / Availability
~Wednesday April 24th~ Confirmed that he is open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by chrissyrissmeyer** [comment]
Action: check with Chris to see if someone is able to present on Tuesday

**Comment by rsteans** [comment]
Chris has confirmed.

**Comment by chrissyrissmeyer** [comment]
Chris is now available Tuesday.
