### ISSUE TITLE
Rethinking metadata design and management

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#30]
## Name
Arwen Hutt

## Institution
UC San Diego

## Names of co-presenter(s)
Ruth Tilman

## Title
Rethinking metadata design and management

## Abstract
For metadata specialists, creating metadata profiles, system requirements, and accompanying documentation often feels like a game of whack-a-mole. Current practices and technologies also mean comparing your profiles with another institutions’ is an enormous hassle. To address this problem, developers and metadatists came together to create the machine-readable metadata modeling (M3) specification. This presentation will offer some history and use cases for the specification, an update on its current status, and where to learn more.

## Audience
Metadata Specialists

## Format 
Longer presentation (approximately 20-30 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by chrissyrissmeyer** [comment]
Asked Arwen if this could be a lightning talk instead and she was fine with this. Will make the changes to the labels.
