### ISSUE TITLE
Samvera Steering Update

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#31]
## Name
Jon Dunn

## Institution
Indiana University

## Names of co-presenter(s)
Richard Green

## Title
Samvera Steering Update

## Abstract
The Chair and Chair-Elect of the Samvera Steering Group will discuss the work of Steering in a year of change.  This discussion will cover the recent changes in the structure of Steering and efforts to increase transparency, along with a brief discussion of topics and issues that Steering is working on this year with the Samvera Community.

## Audience
Developers, DevOps and System Administrators, Repository or DAMS Managers, Metadata Specialists, Administrators

## Format 
Lightning talk (less than 10 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
Richard has confirmed.
