### ISSUE TITLE
Hyrax Batch Ingest: A gem in use

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#6]
## Name
Sadie Roosa

## Institution
WGBH

## Title
Hyrax Batch Ingest: A gem in use

## Abstract
A quick look at how WGBH is using the hyrax-batch_ingest gem in their AMS app for multiple shapes and sizes of ingest.

## Audience
Developers, Repository or DAMS Managers, Metadata Specialists

## Format 
Lightning talk (less than 10 minutes)

## Date preference / Availability
Wednesday April 24th

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
Sadie would prefer the 24th, and if it is the 23rd, isn't available until 1:30 Eastern
