### ISSUE TITLE
Samvera Fundraising Working Group Update

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#7]
## Name
Jon Dunn

## Institution
Indiana University

## Title
Samvera Fundraising Working Group Update

## Abstract
Update on the activities of the Samvera Fundraising Working Group

## Audience
Administrators

## Format 
Interest Group / Working Group update (less than 5 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by chrissyrissmeyer** [comment]
Chris confirmed that he could present on Tuesday.
