### ISSUE TITLE
U-M Digital Collections by the Numbers

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#8]
## Name
John Weise

## Institution
University of Michigan

## Title
U-M Digital Collections by the Numbers

## Abstract
6,761,224,773 words. 2,823,957 images. 200+ content sources. And a very long tail of unique metadata fields. This will be a "by the numbers" tour of the digital collections at the University of Michigan Library that highlights some of the challenges of designing and building a new repository and access system for our digital collections that can handle scale, variety, growth, and a rich feature set.

## Audience
Developers, Repository or DAMS Managers

## Format 
Longer presentation (approximately 20-30 minutes)

## Date preference / Availability
Open to either day

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by jweise** [comment]
Either day is still fine, except not before 10am on Thu the 25th.  Thanks

**Comment by rsteans** [comment]
thanks, John!
