### ISSUE TITLE
From Institutional Repository to Digital Collections Management: Replacing CONTENTdm with Samvera/Hyrax

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/samvera-virtual-connect#9]
## Name
Kathryn Michaelis

## Institution
Georgia State University Library

## Names of co-presenter(s)
Jon Bodnar

## Title
From Institutional Repository to Digital Collections Management: Replacing CONTENTdm with Samvera/Hyrax

## Abstract
Since May 2018, the Georgia State University Library has been developing an instance of Samvera/Hyrax to replace CONTENTdm for digital collections management. After using CONTENTdm for more than a decade, certain features have become indispensable to our digital collections’ workflow. A key part of our development effort has been deciding which features to build into (or to remove from) Samvera/Hyrax. In this presentation, we will discuss how we have balanced updating and preserving workflows, and we will review some of the features we are implementing, including support for controlled vocabularies, oral history ingest and display, and bulk uploading.

## Audience
Repository or DAMS Managers, Metadata Specialists, Administrators

## Format 
Lightning talk (less than 10 minutes)

## Date preference / Availability
Tuesday April 23rd

## Streaming/Recording/Archiving Permission
Yes, I consent to having my session live streamed, recorded, and archived.

**Comment by rsteans** [comment]
COnfirmed Tuesday via email
